### ISSUE TITLE
"Send a mail to all members of my club"

### ISSUE THREAD

**Issue by BenoitDeVrieze** [ZeusWPI/FK-enrolment#41] opened 2015-04-08 23:39 UTC
Excel export + manually copying adresses to the BCC field of a mail is a cumbersome user experience. In addition many mail clients and mail transfer agents limit the number of recipients of message to suppress the spread of spam.

Is this feasible in the context of enrollment? Or should this be considered as a separate project which consumes the member information in enrollment?

A major concern is ofcourse the protection of the emailadresses of the members. Sending mail to the people registered in enrollment should be restricted to the managers of their club.

**Comment by Silox** [comment] 2015-04-09 09:20
Duplicate of #19

**Closed by Silox** 2015-04-09 09:20 UTC
